from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove

btnMainMenu = KeyboardButton('⛺Главное меню')
btnBackinQuest =KeyboardButton('⏩Назад к квестам')
#MainMenu
btnInfo = KeyboardButton('📚 Информация')
btnQuest = KeyboardButton('📌 Квесты')
mainMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnInfo, btnQuest)


#QuestMenu
btnPrapor = KeyboardButton ('🔫Прапор')
btnTerapevt = KeyboardButton ('💊Терапевт')
btnSkypjik = KeyboardButton ('🛒Скупщик')
btnLijnik = KeyboardButton ('🗻Лыжник')
btnMirotvorec = KeyboardButton ('🎯Миротворец')
btnMechanic = KeyboardButton ('🔧Механик')
btnBarahol = KeyboardButton ('🧻Барахольщик')
btnEgor = KeyboardButton ('🪓Егерь')
questMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPrapor, btnTerapevt, btnSkypjik, btnLijnik, btnMirotvorec, btnMechanic, btnBarahol, btnEgor, btnMainMenu)

#Квесты терапевта
btn_qvest_terapevt_1 = KeyboardButton('Дефицит')
btn_qvest_terapevt_2 = KeyboardButton('Операция «Водолей». Часть 1')
btn_qvest_terapevt_3 = KeyboardButton('Операция «Водолей». Часть 2')
btn_qvest_terapevt_4 = KeyboardButton('Санэпиднадзор. Часть 1')
btn_qvest_terapevt_5 = KeyboardButton('Санэпиднадзор. Часть 2')
btn_qvest_terapevt_6 = KeyboardButton('Пейнкиллер')
btn_qvest_terapevt_7 = KeyboardButton('Провизор')
btn_qvest_terapevt_8 = KeyboardButton('Авторем')
btn_qvest_terapevt_9 = KeyboardButton('Клятва Гиппократа')
btn_qvest_terapevt_10 = KeyboardButton('Медицинский журнал')
btn_qvest_terapevt_11 = KeyboardButton('Планы снабжения')
btn_qvest_terapevt_12 = KeyboardButton('Врачебная тайна. Часть 1')
btn_qvest_terapevt_13 = KeyboardButton('Врачебная тайна. Часть 2')
btn_qvest_terapevt_14 = KeyboardButton('Врачебная тайна. Часть 3')
btn_qvest_terapevt_15 = KeyboardButton('В здоровом теле здоровый дух')
btn_qvest_terapevt_16 = KeyboardButton('Врачебная тайна. Часть 4')
btn_qvest_terapevt_17 = KeyboardButton('Физкультурник')
btn_qvest_terapevt_18 = KeyboardButton('Частная клиника')
btn_qvest_terapevt_19 = KeyboardButton('Врачебная тайна. Часть 5')
btn_qvest_terapevt_20 = KeyboardButton('Служба дезинфекции')



btnskip_terapevt_1 = KeyboardButton('💊2/5➡')
btnskip_terapevt_2 = KeyboardButton('💊3/5➡')
btnskip_terapevt_3 = KeyboardButton('💊4/5➡')
btnskip_terapevt_4 = KeyboardButton('💊5/5➡')
btnskip_back_terapevt_1 = KeyboardButton('⬅1/5💊')
btnskip_back_terapevt_2 = KeyboardButton('⬅2/5💊')
btnskip_back_terapevt_3 = KeyboardButton('⬅3/5💊')
btnskip_back_terapevt_4 = KeyboardButton('⬅4/5💊')
terapevtMenu1 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_terapevt_1, btn_qvest_terapevt_2, btn_qvest_terapevt_3, btn_qvest_terapevt_4, btn_qvest_terapevt_5, btn_qvest_terapevt_6, btn_qvest_terapevt_7, btn_qvest_terapevt_8, btn_qvest_terapevt_9, btnBackinQuest, btnMainMenu, btnskip_terapevt_1)
terapevtMenu2 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_terapevt_10, btn_qvest_terapevt_11, btn_qvest_terapevt_12, btn_qvest_terapevt_13, btn_qvest_terapevt_14, btn_qvest_terapevt_15, btn_qvest_terapevt_16, btn_qvest_terapevt_17, btnBackinQuest,btnskip_back_terapevt_1, btnMainMenu, btnskip_terapevt_2)
terapevtMenu3 = ReplyKeyboardMarkup(resize_keyboard=True).add()



#Квесты механика
btn_qvest_mechanic_1 = KeyboardButton('Поручение')
btn_qvest_mechanic_2 = KeyboardButton('Оружейник. Часть 1 (МР-133)')
btn_qvest_mechanic_3 = KeyboardButton('Оружейник. Часть 2 (АКС-74У)')
btn_qvest_mechanic_4 = KeyboardButton('Оружейник. Часть 3 (MP5)')
btn_qvest_mechanic_5 = KeyboardButton('Оружейник. Часть 4 (M4A1)')
btn_qvest_mechanic_6 = KeyboardButton('Оружейник. Часть 5 (ДВЛ-10)')
btn_qvest_mechanic_7 = KeyboardButton('Оружейник. Часть 6 (R11 RSASS)')
btn_qvest_mechanic_8 = KeyboardButton('Оружейник. Часть 7 (Remington M870)')
btn_qvest_mechanic_9 = KeyboardButton('Оружейник. Часть 8 (АКМ)')
btn_qvest_mechanic_10 = KeyboardButton('Оружейник. Часть 9 (АКС-74Н)')
btn_qvest_mechanic_11 = KeyboardButton('Оружейник. Часть 10 (АК-105)')
btn_qvest_mechanic_12 = KeyboardButton('Оружейник. Часть 11 (АС Вал)')
btn_qvest_mechanic_13 = KeyboardButton('Оружейник. Часть 12 (АК-102)')
btn_qvest_mechanic_14 = KeyboardButton('Оружейник. Часть 13 (SIG MPX)')
btn_qvest_mechanic_15 = KeyboardButton('Оружейник. Часть 14 (АКМН)')
btn_qvest_mechanic_16 = KeyboardButton('Оружейник. Часть 15 (M1A)')
btn_qvest_mechanic_17 = KeyboardButton('Оружейник. Часть 16 (M4A1)')
btn_qvest_mechanic_18 = KeyboardButton('Сигнал. Часть 1')
btn_qvest_mechanic_19 = KeyboardButton('Свой человек')
btn_qvest_mechanic_20 = KeyboardButton('Сигнал. Часть 2')
btn_qvest_mechanic_21 = KeyboardButton('Скаут')
btn_qvest_mechanic_22 = KeyboardButton('Военный хабар')
btn_qvest_mechanic_23 = KeyboardButton('Чёрный выход')
btn_qvest_mechanic_24 = KeyboardButton('Сигнал. Часть 3')
btn_qvest_mechanic_25 = KeyboardButton('Сигнал. Часть 4')
btn_qvest_mechanic_26 = KeyboardButton('Садоводство. Часть 1')
btn_qvest_mechanic_27 = KeyboardButton('Садоводство. Часть 2')
btn_qvest_mechanic_28 = KeyboardButton('Вредная привычка')
btn_qvest_mechanic_29 = KeyboardButton('Садоводство. Часть 3')
btn_qvest_mechanic_30 = KeyboardButton('Садоводство. Часть 4')
btn_qvest_mechanic_31 = KeyboardButton('Снайпер-психопат')
btn_qvest_mechanic_32 = KeyboardButton('Стрелок от бога')
btn_qvest_mechanic_33 = KeyboardButton('Удобрения')
btn_qvest_mechanic_34 = KeyboardButton('Импорт')
btn_qvest_mechanic_35 = KeyboardButton('Кабинет химии')
btn_qvest_mechanic_36 = KeyboardButton('Пристрелка')
btn_qvest_mechanic_37 = KeyboardButton('Курьер')
btn_qvest_mechanic_38 = KeyboardButton('Тайны Корпоратов')
btn_qvest_mechanic_39 = KeyboardButton('Энергетический кризис')


btnskip_mechanic_1 = KeyboardButton('🔧2/5➡')
btnskip_mechanic_2 = KeyboardButton('🔧3/5➡')
btnskip_mechanic_3 = KeyboardButton('🔧4/5➡')
btnskip_mechanic_4 = KeyboardButton('🔧5/5➡')
btnskip_back_mechanic_1 = KeyboardButton('⬅1/5🔧')
btnskip_back_mechanic_2 = KeyboardButton('⬅2/5🔧')
btnskip_back_mechanic_3 = KeyboardButton('⬅3/5🔧')
btnskip_back_mechanic_4 = KeyboardButton('⬅4/5🔧')
mechanicMenu1 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_mechanic_1, btn_qvest_mechanic_2, btn_qvest_mechanic_3, btn_qvest_mechanic_4, btn_qvest_mechanic_5, btn_qvest_mechanic_6, btn_qvest_mechanic_7, btn_qvest_mechanic_8, btn_qvest_mechanic_9, btnBackinQuest, btnMainMenu, btnskip_mechanic_1)
mechanicMenu2 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_mechanic_10, btn_qvest_mechanic_11, btn_qvest_mechanic_12, btn_qvest_mechanic_13, btn_qvest_mechanic_14, btn_qvest_mechanic_15, btn_qvest_mechanic_16, btn_qvest_mechanic_17, btnBackinQuest,btnskip_back_mechanic_1, btnMainMenu, btnskip_mechanic_2)
mechanicMenu3 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_mechanic_18, btn_qvest_mechanic_19, btn_qvest_mechanic_20, btn_qvest_mechanic_21, btn_qvest_mechanic_22, btn_qvest_mechanic_23, btn_qvest_mechanic_24, btn_qvest_mechanic_25, btnBackinQuest,btnskip_back_mechanic_2, btnMainMenu, btnskip_mechanic_3)
mechanicMenu4 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_mechanic_26, btn_qvest_mechanic_27, btn_qvest_mechanic_28, btn_qvest_mechanic_29, btn_qvest_mechanic_30, btn_qvest_mechanic_31, btn_qvest_mechanic_32, btn_qvest_mechanic_33, btnBackinQuest,btnskip_back_mechanic_3, btnMainMenu, btnskip_mechanic_4)
mechanicMenu5 = ReplyKeyboardMarkup(resize_keyboard=True).add(btn_qvest_mechanic_34, btn_qvest_mechanic_35, btn_qvest_mechanic_36, btn_qvest_mechanic_37, btn_qvest_mechanic_38, btn_qvest_mechanic_39, btnBackinQuest, btnMainMenu, btnskip_back_mechanic_4)
